-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 23:26:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema babysittersdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema babysittersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `babysittersdb` DEFAULT CHARACTER SET utf8 ;
USE `babysittersdb` ;

-- -----------------------------------------------------
-- Table `babysittersdb`.`aptitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babysittersdb`.`aptitudes` (
  `id` INT NULL AUTO_INCREMENT,
  `aptitudes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `babysittersdb`.`ciudad_de_residencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babysittersdb`.`ciudad_de_residencias` (
  `id` INT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `babysittersdb`.`babysitters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babysittersdb`.`babysitters` (
  `id` INT NULL AUTO_INCREMENT,
  `img` VARCHAR(100) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(60) NULL,
  `edad` TINYINT(150) NULL,
  `paisDeResidencia` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `celular` INT NULL,
  `descripcion` TEXT(500) NULL,
  `frase` VARCHAR(80) NULL,
  `precio` INT NULL,
  `ciudad_de_residencias_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_babysitters_ciudad_de_residencias1_idx` (`ciudad_de_residencias_id` ASC),
  CONSTRAINT `fk_babysitters_ciudad_de_residencias1`
    FOREIGN KEY (`ciudad_de_residencias_id`)
    REFERENCES `babysittersdb`.`ciudad_de_residencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `babysittersdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babysittersdb`.`users` (
  `id` INT NULL AUTO_INCREMENT,
  `img` VARCHAR(100) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(60) NULL DEFAULT NULL,
  `paisDeResidencia` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `movil` INT NULL DEFAULT NULL,
  `pregunta` TINYINT(4) NULL DEFAULT NULL,
  `dudas` VARCHAR(45) NULL DEFAULT NULL,
  `admin` TINYINT(4) NULL DEFAULT NULL,
  `ciudad_de_residencias_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_ciudad_de_residencias1_idx` (`ciudad_de_residencias_id` ASC),
  CONSTRAINT `fk_users_ciudad_de_residencias1`
    FOREIGN KEY (`ciudad_de_residencias_id`)
    REFERENCES `babysittersdb`.`ciudad_de_residencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `babysittersdb`.`carrito_de_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babysittersdb`.`carrito_de_compras` (
  `id` INT NULL AUTO_INCREMENT,
  `cantidad` TINYINT(10) NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `babysitters_id` INT NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrito_de_compras_babysitters1_idx` (`babysitters_id` ASC),
  INDEX `fk_carrito_de_compras_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_carrito_de_compras_babysitters1`
    FOREIGN KEY (`babysitters_id`)
    REFERENCES `babysittersdb`.`babysitters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_de_compras_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `babysittersdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `babysittersdb`.`babysitters_has_aptitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `babysittersdb`.`babysitters_has_aptitudes` (
  `babysitters_id` INT NULL,
  `aptitudes_id` INT NULL,
  PRIMARY KEY (`babysitters_id`, `aptitudes_id`),
  INDEX `fk_babysitters_has_aptitudes_aptitudes1_idx` (`aptitudes_id` ASC) ,
  INDEX `fk_babysitters_has_aptitudes_babysitters1_idx` (`babysitters_id` ASC),
  CONSTRAINT `fk_babysitters_has_aptitudes_babysitters1`
    FOREIGN KEY (`babysitters_id`)
    REFERENCES `babysittersdb`.`babysitters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_babysitters_has_aptitudes_aptitudes1`
    FOREIGN KEY (`aptitudes_id`)
    REFERENCES `babysittersdb`.`aptitudes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





